cs412/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('quotes/', include('quotes.urls')),
    path('restaurant/', include('restaurant.urls')),
    path('mini_fb/', include('mini_fb.urls')),    
    path('voter_analytics/', include('voter_analytics.urls')),
    path('project/', include('project.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/urls.py
from django.urls import path
from .views import QuestionListView, QuestionDetailView, TriviaAttemptListView, TriviaAttemptDetailView, CategorySelectionView, QuestionCategoryListView, ShowProfilePageView, CreateProfileView, RedirectToProfileView, QuestionCreateView, TriviaAttemptView, TriviaLeaderboardView, QuestionEditView, TriviaScoreGraphView, QuestionDeleteView, HomePageView
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
from django.conf import settings

# Emmanuel Eyob emanzman@bu.edu

urlpatterns = [
    path('', HomePageView.as_view(), name='home'),
    path('categories/', CategorySelectionView.as_view(), name='category_selection'),
    path('questions/', QuestionListView.as_view(), name='question_list'),
    path('questions/<int:pk>/', QuestionDetailView.as_view(), name='question_detail'),
    path('attempts/', TriviaAttemptListView.as_view(), name='attempt_list'),
    path('attempts/<int:pk>/', TriviaAttemptDetailView.as_view(), name='attempt_detail'),
    path('category/<str:category>/', QuestionCategoryListView.as_view(), name='category_questions'),
    path('login/', auth_views.LoginView.as_view(template_name='project/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
    path('profile/<int:pk>/', ShowProfilePageView.as_view(), name='show_profile'),
    path('create_profile/', CreateProfileView.as_view(), name='create_profile'),
    path('redirect/', RedirectToProfileView.as_view(), name='redirect_to_profile'),
    path('questions/create/', QuestionCreateView.as_view(), name='create_question'),
    path('trivia_attempt/<str:category>/', TriviaAttemptView.as_view(), name='trivia_attempt'),
    path('trivia_leaderboard/', TriviaLeaderboardView.as_view(), name='trivia_leaderboard'),
    path('questions/<int:pk>/edit/', QuestionEditView.as_view(), name='edit_question'),
    path('profile/<int:profile_pk>/triviascore-graph/<str:category>/', TriviaScoreGraphView.as_view(), name='triviascore_graph'),
    path('questions/<int:pk>/delete/', QuestionDeleteView.as_view(), name='delete_question'),



]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/models.py
from django.db import models
from django.contrib.auth.models import User

# Emmanuel Eyob emanzman@bu.edu
# Models for Ethiopian Trivia App
# Create your models here.

# Adds additional fields to built-in Django User model
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='project_profile') # One user can only have one profile
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return f"{self.user.username}'s Profile"

# Stores trivia questions, their category, creator info, and an optional image
class Question(models.Model):
  category_choices = [
        ('music', 'Music'),
        ('history', 'History'),
        ('geography', 'Geography'),
  ] # First value in tuple is the value stored in the database and the second value is the label shown thorughout the app and in the drop down menus
  
  question_text = models.TextField() 
  category = models.CharField(choices=category_choices)
  question_creator = models.ForeignKey(User, on_delete=models.CASCADE)
  image = models.ImageField(blank=True, null=True)

  def __str__(self):
    return self.question_text
  
# Stores and represent the multiple choices from each question 
class QuestionChoice(models.Model):
  question = models.ForeignKey(Question, on_delete=models.CASCADE, related_name='choices')
  choice_text = models.CharField()
  correct_choice = models.BooleanField(default=False)  

  def __str__(self):
    correct_checker = "Correct" if self.correct_choice else "Incorrect"
    return f"{self.choice_text} ({correct_checker})"

# Stores values related to a user's trivia attempt such as the user, category, trivia score, and the attempt date
class TriviaAttempt(models.Model):
  category__dropdown = Question.category_choices

  user = models.ForeignKey(User, on_delete=models.CASCADE)
  category = models.CharField(choices=category__dropdown)
  score = models.IntegerField()
  attempt_date = models.DateTimeField()

  def __str__(self):
    return f"{self.user.username} | Category: {self.category} | Score: {self.score}"

# Stores the answer the user chose from each multiple choice question attempt
class QuestionAnswer(models.Model):
  trivia_attempt = models.ForeignKey(TriviaAttempt, on_delete=models.CASCADE)
  question = models.ForeignKey(Question, on_delete=models.CASCADE)
  user_choice = models.ForeignKey(QuestionChoice, on_delete=models.CASCADE)

  def __str__(self):
    return f"{self.user_choice} | Question: {self.question} | User: {self.trivia_attempt}"
  

project/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import TriviaAttempt, Profile, Question, QuestionChoice

# Emmanuel Eyob emanzman@bu.edu

# Form page for Ethiopian Trivia App

# Form that handles user registration
class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        # Values displayed in the registration form
        fields = ['username', 'first_name', 'last_name', 'email', 'password1', 'password2']

# Adding a profile image upload form to be combined with the user creation form
class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image']

# Form to create and modify a trivia attempt
class TriviaAttemptForm(forms.ModelForm):
    class Meta:
        model = TriviaAttempt
        fields = ['category', 'score']

# Form to create a trivia question with question text, category, choices, and an optional image
class QuestionCreationForm(forms.ModelForm):

    # Fields to enter 4 choices for the question
    choice1 = forms.CharField(label='Choice 1')
    choice2 = forms.CharField(label='Choice 2')
    choice3 = forms.CharField(label='Choice 3')
    choice4 = forms.CharField(label='Choice 4')

    # Radio button selection of the correct choice
    correct_choice = forms.ChoiceField(
        label='Correct Choice',
        choices=[('1', 'Choice 1'), ('2', 'Choice 2'), ('3', 'Choice 3'), ('4', 'Choice 4')],
        widget=forms.RadioSelect
    )
    class Meta:
        model = Question
        fields = ['question_text', 'category', 'image']

# From used for category dropdown on leaderboard page
class CategoryFilterForm(forms.Form):
    all_categories = 'all'
    category = forms.ChoiceField(choices=[('', 'Choose a category'), (all_categories, 'All Categories'),] + list(Question.category_choices), required=True)

# From uses for editting a question
class QuestionEditForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'category', 'image']

project/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView, DetailView, TemplateView, CreateView, UpdateView, FormView, DeleteView
from .models import Question, TriviaAttempt, Profile, QuestionChoice, QuestionAnswer
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth import login
from .forms import UserRegisterForm, ProfileForm, QuestionCreationForm, CategoryFilterForm, QuestionEditForm
from django.views import View
from django.utils import timezone
from django.urls import reverse
from plotly.offline import plot
import plotly.graph_objs as go
from collections import Counter
from django.db.models import Avg, Max, Min

# Emmanuel Eyob emanzman@bu.edu
# Views page for Ethiopian Trivia App.
# Create your views here.

# View that displays list of questions for users with staff privelleges
class QuestionListView(UserPassesTestMixin,ListView):
    model = Question
    template_name = 'project/question_list.html'
    context_object_name = 'questions'

    def test_func(self):
      # This checks if the authenticated user has staff privelleges
      return self.request.user.is_authenticated and self.request.user.is_staff
    
    def handle_no_permission(self):
        # Redirects users to homepage if they don't have staff privelleges
        return redirect('category_selection')

# View that displays a list of questions in a category 
class QuestionCategoryListView(ListView):
    model = Question
    template_name = 'project/question_list.html'
    context_object_name = 'questions'

    def get_queryset(self):
      category = self.kwargs['category']
      return Question.objects.filter(category=category)

# View displaying a list of categories to choose from
class CategorySelectionView(TemplateView):
    template_name = 'project/category_selection.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Question.category_choices
        return context

# View that displayes the details of a question and its choices
class QuestionDetailView(DetailView):
    model = Question
    template_name = 'project/question_detail.html'
    context_object_name = 'question'

# View that lists all trivia attempts from a user
class TriviaAttemptListView(ListView):
    model = TriviaAttempt
    template_name = 'project/triviaattempt_list.html'
    context_object_name = 'attempts'

# View that displays detailed information about a specific trivia attempt
class TriviaAttemptDetailView(DetailView):
    model = TriviaAttempt
    template_name = 'project/triviaattempt_detail.html'
    context_object_name = 'attempt'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context

# View that handles user registration and profile creation together
class CreateProfileView(CreateView):   
    template_name = 'project/create_profile_form.html'

    def get(self, request, *args, **kwargs):
        # Redirects user to their profile page if they are logged in and have a proifle
        if request.user.is_authenticated and Profile.objects.filter(user=request.user).exists():
            profile = Profile.objects.get(user=request.user)
            return redirect('show_profile', pk=profile.pk)
        
        # Renders registration and profile forms that are blank
        user_form = UserRegisterForm()
        profile_form = ProfileForm()
        return render(request, self.template_name, {
            'form': user_form,
            'profile_form': profile_form
        })

    def post(self, request, *args, **kwargs):
        # Handles new user and profile registration forms
        user_form = UserRegisterForm(request.POST)
        profile_form = ProfileForm(request.POST, request.FILES)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save() # Saves form
            login(request, user) # Logs user in
            profile = profile_form.save(commit=False) # Creates profile instance but doesn't save to database yet
            profile.user = user # Links profile to user
            profile.save() # Saves profile
            return redirect('show_profile', pk=profile.pk) # Redirects to user's profile page
        
        # Renders form again if the form is invalid
        return render(request, self.template_name, {
            'form': user_form,
            'profile_form': profile_form
        })
    
# View that redirects logged in users to their profile page if it exists and if it doesn't exist, it redirects them to the profile creation page
class RedirectToProfileView(LoginRequiredMixin, View):
    def get(self, request, *args, **kwargs):
        try:
            profile = Profile.objects.get(user=request.user)
            return redirect('show_profile', pk=profile.pk)
        except Profile.DoesNotExist:
            return redirect('create_profile')

# View that shows a user's profile with the profile model
class ShowProfilePageView(LoginRequiredMixin, DetailView):
    model = Profile
    template_name = 'project/profile.html'
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Gets all trivia attempts from a user ordered by latest to oldest
        attempts = TriviaAttempt.objects.filter(user=self.object.user).order_by('-attempt_date')
        context['trivia_attempts'] = attempts

        # Stores list of different categories attempted by a user
        categories_attempted = []
        for attempt in attempts:
            if attempt.category not in categories_attempted:
                categories_attempted.append(attempt.category)
        context['categories_attempted'] = categories_attempted
        
        badges = []

        # Perfectionist badge if user ever scored 100
        if attempts.filter(score=100).exists():
            badges.append("Perfectionist | Scored 100 on a trivia attempt")

        # Dedicated badge if user attempted trivia 5 or more times
        if attempts.count() >= 5:
            badges.append("Dedicated | Completed 5+ trivia attempts")

        # Veteran badge if user attempted 10 or more trvia games
        if attempts.count() >= 10:
            badges.append("Veteran | Completed 10+ trivia attempts")

        # Versatile badge if user attempted 3 or more different categories
        if len(categories_attempted) >= 3:
            badges.append("Versatile | Attempted 3+ different categories")

        # Improver badge if latest score is higher than initial score
        if attempts.count() >= 2:
            latest_score = attempts.first().score 
            earliest_score = attempts.last().score
            if latest_score > earliest_score:
                badges.append("Improver | Improved score from first to lastest score")
    
        context['badges'] = badges

        # Trivia stats for players
        total_attempts = attempts.count() # Total number of trivia attempts
        avg_score = attempts.aggregate(Avg('score'))['score__avg'] or 0 # Average score of trivia attemmpts
        highest_score = attempts.aggregate(Max('score'))['score__max'] or 0 # Highest trivia score across every category
        lowest_score = attempts.aggregate(Min('score'))['score__min'] or 0 # Lowest trivia score across every category

        # Category that is most attempted
        category_ctr = Counter(attempt.category for attempt in attempts)
        most_attempted_category = category_ctr.most_common(1)[0][0] if category_ctr else None

        number_categories = len(categories_attempted) # Number of attempted categories

        # Average score based on category
        category_averages = {}
        for category in categories_attempted:
            avg = TriviaAttempt.objects.filter(user=self.object.user, category=category).aggregate(Avg('score'))['score__avg'] or 0
            category_averages[category] = round(avg, 2)

        if category_averages:

            # Radar Graph
            figure = go.Figure(
                data=go.Scatterpolar(
                    r=list(category_averages.values()),
                    theta=list(category_averages.keys()),
                    fill='toself'
                )
            )
            context['radar_div'] = plot(figure, output_type='div')

            # Bar Graph
            bar_figure = go.Figure(
                data=go.Bar(
                    x=list(category_averages.keys()),
                    y=list(category_averages.values()),
                )
            )
            context['bar_div'] = plot(bar_figure, output_type='div')


        context['player_trivia_stats'] = {
            'total_attempts': total_attempts,
            'avg_score': round(avg_score, 2),
            'highest_score': highest_score,
            'lowest_score': lowest_score,
            'most_attempted_category': most_attempted_category,
            'number_categories': number_categories,
            'category_averages': category_averages,
        }

        
        return context
    
       
# View that lets staff users create questions
class QuestionCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Question
    form_class = QuestionCreationForm
    template_name = 'project/question_creation.html'

    def test_func(self):
        # Checks if logged in user is staff
        return self.request.user.is_staff

    def form_valid(self, form):
        question = form.save(commit=False) # Creates a question object from form data but doesn't save yet
        question.question_creator = self.request.user # Assigns logged in user as quesetion creator
        question.save() # Saves question to db with question creator added

        # Gets question choices from form and creates the 4 choices
        choices = [
            form.cleaned_data['choice1'],

project/templates/project/base.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Base html file for Ethiopian Trivia Web App-->
<!-- Displays navbar across all pages and a block content wrapped around a div with class container-->
{% load static %}

<html>
  <head>
    <title>Ethiopian Trivia App</title>
    <link rel="stylesheet" href="{% static 'styles5.css' %}">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Fira+Sans+Condensed:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,500;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet">
  </head>
  <body>
    <nav>
    <div class="nav-left">  
      Ethiopian Trivia App
    </div>
    <div class="nav-regular">
      <a href="{% url 'home' %}">Home</a>
      {% if user.is_authenticated %}
        <a href="{% url 'category_selection' %}">Play</a>
      {% endif %}

      {% if user.is_authenticated and user.is_staff %}
        <a href="{% url 'question_list' %}">All Questions</a>
        <a href="{% url 'create_question' %}">Create Question</a>
      {% endif %}

      <a href="{% url 'attempt_list' %}">Trivia Attempts</a>
      <a href="{% url 'trivia_leaderboard' %}">Leaderboard</a>

      {% if user.is_authenticated and user.project_profile %}
        <a href="{% url 'show_profile' user.project_profile.pk %}">Profile</a>
        <form method="post" action="{% url 'logout' %}">
          {% csrf_token %}
          <button type="submit">Logout</button>
        </form>
        
      {% else %}
        <a href="{% url 'login' %}">Login</a>
        <a href="{% url 'create_profile' %}">Create Profile</a>
      {% endif %}
  </div>
  </nav>
  <div class="container">
    {% block content %}
    {% endblock %}
    </div>
  </body>
</html>

project/templates/project/category_selection.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Category Selection Page for Ethiopian Trivia Web App -->
<!-- Users start the trivia attempt on this page and see instructions on how to play, features, and badges-->

{% extends 'project/base.html' %}

{% block content %}
<div class="content-container">
    <h1>🇪🇹 Welcome to the Ethiopian Trivia App 🇪🇹</h2><br>
    <h2>Pick an Ethiopian Trivia Category to Start Playing</h2>
    <div class="category-button-container">
        {% for val, category_label in categories %}
                <a class="category-button" href="{% url 'trivia_attempt' val %}">{{ category_label }}</a></li>
        {% endfor %}
    </div>
    <br>
    <div class="horizontal-category-section">
        <div class="category-section">
            <h2>How to Play Ethiopian Trivia</h2>
            <ol>
                <li>Click the link in a category to choose which category to play in</li>
                <li>Answer the 20 questions in your category and finish the quiz</li>
                <li>You get 5 points for each correct answer and it is scored out of 100</li>
                <li>View the details of your quiz and see where you stand on the leaderboard</li>
            </ol>
        </div>

        <div class="category-section">
            <h2>Features of the Ethiopian Trivia App</h2>
            <ul>
                <li>Take a trivia quiz in a category of your choice and learn about Ethiopia</li>
                <li>Track your trivia score and view your progress</li>
                <li>View your trivia scores visually with a graph</li>
                <li>Compete with other users on the leaderboard</li>
                <li>Earn badges for your trivia attempts</li>
            </ul>
        </div>

        <div class="category-section">
            <h2>Badges You Can Earn</h2>
            <ul>
                <li>Perfectionist | Scored 100 on a trivia attempt</li>
                <li>Dedicated | Completed 5+ trivia attempts</li>
                <li>Veteran | Completed 10+ trivia attempts</li>
                <li>Versatile | Attempted 3+ different categories</li>
                <li>Improver | Improved score from first to lastest score</li>
            </ul>
        </div>
    </div>

</div>
{% endblock %}

project/templates/project/create_profile_form.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page to Create a Profile for the Ethiopian Trivia App -->

{% extends "project/base.html" %}

{% block content %}

<div class="form-container">
  <h1>Create a Profile</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    {{ profile_form.as_p }}
    <button type="submit">Create Profile</button>
  </form>
</div>



{% endblock %}

project/templates/project/delete_confirmation.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page showing confirmation of deleting a question -->

{% extends 'project/base.html' %}

{% block content %}
<div class="content-container">
  <h1>Are you sure you want to delete this question?</h1>
  <p>{{ question.question_text }}</p>

  {% if question.image %}
    <img src="{{ question.image.url }}">
  {% endif %}

  <form method="post">
    {% csrf_token %}
    <button type="submit">Delete</button>
    <a href="{% url 'question_list' %}">Go Back</a>
  </form>
</div>
{% endblock %}

project/templates/project/edit_question.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page to Edit a Question for Ethiopian Trivia Web App-->

{% extends 'project/base.html' %}

{% block content %}
<div class="form-container">
  <h1>Edit Question</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}

    {% for choice in choices %}
    <div class="choice-row">
      <label>Choice {{ forloop.counter }}</label>
      <input class="edit-question-choice-input"type="text" name="choice_{{ choice.id }}" value="{{ choice.choice_text }}">
      <input type="radio" name="correct_choice" value="{{ choice.id }}" {% if choice.correct_choice %}checked{% endif %}> Correct<br>
    </div>
    {% endfor %}
    <button type="submit">Save</button>
  </form>
</div>
{% endblock %}

project/templates/project/home.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Home page for Ethiopian Trivia App -->
<!-- This paes shows background information about Ethiopia, facts, instructions on how to play the trivia game, and features of the app-->

{% extends 'project/base.html' %}

{% block content %}
<div class="content-container">

  <h1>🇪🇹 Welcome to the Ethiopian Trivia App 🇪🇹</h1><br>

  <h2>About Ethiopia</h2>
  <p>Ethiopia, located in East Africa, is one of the oldest nations in the world. It is known for its diverse cultures, history, unique calendar, and landscapes.</p>
  <p>Some of its landmarks include the Simien Mountains, Rock-Hewn Churches of Lalibela, and obleisks in Axum.</p>
  <p>Ethiopia's culture is vibrant with its traditinonal coffee ceremony, unique cuisine, music, and religious identity.</p>


  <h2>Facts About Ethiopia:</h2>
  <ul>
      <li>Ethiopa is the only African country that was never colonized.</li><br>
      <li>Coffee was discovered in Ethiopia.</li><br>
      <li>Ethiopia has 13 months in its calendar.</li><br>
      <li>Ethiopia has its own script called Ge'ez.</li><br>
      <li>Addis Ababa has the highest altitude capital city in Africa.</li><br>
      <li>The African Union is headquartered in Addis Ababa, Ethiopia.</li><br>
      <li>The Ethiopian calendar is 7-8 years behind the Gregorian calendar.</li><br>
      <li>The Blue Nile River starts in Ethiopia.</li><br>
      <li>Axum is a city in Ethiopia that is believed to hold the Ark of the Covenant.</li><br>
      <li>Ethiopia is the birthplace of the oldest human ancestor Lucy.</li><br>
      <li>The Danakil Depression, found in Ethiopia, is one of the hottest places on Earth.</li>
  </ul>


  <h2>How to Play Ethiopian Trivia</h2>
  <ol>
      <li>Click the link in a category to choose which category to play in</li>
      <li>Answer the 20 questions in your category and finish the quiz</li>
      <li>You get 5 points for each correct answer and it is scored out of 100</li>
      <li>View the details of your quiz and see where you stand on the leaderboard</li>
  </ol>


  <h2>Features of the Ethiopian Trivia App</h2>
  <ul>
      <li>Take a trivia quiz in a category of your choice and learn about Ethiopia</li>
      <li>Track your trivia score and view your progress</li>
      <li>View your trivia scores visually with a graph</li>
      <li>Compete with other users on the leaderboard</li>
      <li>Earn badges for your trivia attempts</li>
  </ul>

</div>
{% endblock %}

  


  

project/templates/project/login.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Login Page for Ethiopian Trivia Web App-->
{% extends 'project/base.html' %}

{% block content %}
<div class="form-container">
  <h1>Login</h1>

  <form action="{% url 'login' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="hidden" name="next" value="{% url 'redirect_to_profile' %}">
    <button type="submit">Login</button>
  </form>
</div>
{% endblock %}

project/templates/project/question_creation.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page to Create Trivia Questions for Ethiopian Trivia Web App-->
<!-- Accessible only to staff users -->

{% extends 'project/base.html' %}
{% block content %}

<div class="form-container">
  <h1>Create a Question</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create Question</button>
  </form>
</div>

{% endblock %}

project/templates/project/question_detail.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page Dsiplaying Detail of a Single Question from the Ethiopian Trivia Web App-->

{% extends 'project/base.html' %}

{% block content %}
<div class="content-container">
  <h1>Question Information</h1>
  <p>{{ question.question_text }}</p>

  {% if question.image %}
      <img src="{{ question.image.url }}">
  {% endif %}

  <h2> Multiple Choice</h2>
  <ul>
    {% for choice in question.choices.all %}
      <li>{{ choice.choice_text }} {% if choice.correct_choice %}(Correct){% endif %}</li>
    {% endfor %}
  </ul>

  <p>Category: {{ question.get_category_display }}</p>
  <p>Created by: {{ question.question_creator }}</p>
</div>
{% endblock %}

project/templates/project/triviaattempt_detail.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page Displaying Detail of a Single Trivia Attempt of the Ethiopian Trivia Web App-->
<!-- Information includes the user's profile, triva attempt category, trivia attempt score, trivia attempt date and question explanations-->

{% extends 'project/base.html' %}

{% block content %}
<div class="content-container">
  <h1>Ethiopian Trivia Attempt Details:</h1>
  <ul>
    <li>User:<a href="{% url 'show_profile' attempt.user.project_profile.pk %}">{{ attempt.user.username }}</a></li>
    <li>Category: {{ attempt.category }}</li>
    <li>Score: {{ attempt.score }}</li>
    <li>Date: {{ attempt.attempt_date }}</li>
  </ul>


  <h2>Question Explanations:</h2>

  {% for answer in attempt.questionanswer_set.all %}
  <p>Question {{ forloop.counter }}: {{ answer.question.question_text }}</p>

  <p>Your Answer: {{ answer.user_choice.choice_text }}</p>
    {% if answer.user_choice.correct_choice %}
      <p>(Correct)</p>
    {% else %}
      <p>(Incorrect)</p>
      <p>Correct Answer:</p>
      {% for choice in answer.question.choices.all %}
        {% if choice.correct_choice %}
          {{ choice.choice_text }}
        {% endif %}
      {% endfor %}
    {% endif %}
  {% endfor %}
</div>
{% endblock %}

project/templates/project/triviaattempt_list.html
<!-- Emmanuel Eyob emanzman@bu.edu-->
<!-- Page Dsiplaying List of all Trivia Attempts of the Ethiopian Trivia Web App-->

{% extends 'project/base.html' %}

{% block content %}
<div class="list-container">
  <h1>Ethiopian Trivia Attempts</h1>
  <ul>
    {% for attempt in attempts %}
    <li>
      <a class="trivia-attempt-link" href="{% url 'attempt_detail' attempt.pk %}">{{ attempt.user.username }} | {{ attempt.category }} | {{attempt.score}}</a><br><br>
    </li>
    {% empty %}
    <li>No trivia attempts yet.</li>
    {% endfor %}
  </ul>
</div>
{% endblock %}